Repository alexthompson207/whats-cookin, pull requests merged in 2021-02, with the labels that each got.

#21 Feature/ingredient class and test
  package-lock.json
  src/ingredient.js
  test/ingredient-test.js
Labels: needs review

#27 Feature/recipe class
  src/recipe.js
  test/recipe-test.js
Labels: iteration 1, needs review

#28 Fix/refactor classes
  .gitignore
  src/ingredient.js
  src/recipe.js
  src/reciperepo.js
  test/ingredient-test.js
  test/recipe-test.js
  test/reciperepo-test.js
Labels: iteration 1, needs review, testing

#29 Feature/main page display
  src/index.html
  src/style.css
Labels: CSS, HTML, iteration 1, needs review

#31 Feature/ingredient repo class and tests
  .prettierrc
  src/ingredientRepo.js
  test/ingredientRepo-test.js
Labels: JavaScript, iteration 1, needs review

#32 Feature/recipe repo class and test
  src/reciperepo.js
  test/recipe-test.js
  test/reciperepo-test.js
Labels: JavaScript, feature, iteration 1, needs review

#33 Feature/single recipe view
  src/index.html
  src/style.css
Labels: CSS, HTML, iteration 1, needs review

#47 Feature/user stories view all recipes
  src/index.html
  src/ingredientRepo.js
  src/recipe.js
  src/reciperepo.js
  src/scripts.js
  src/style.css
  test/recipe-test.js
  test/reciperepo-test.js
Labels: JavaScript, feature, iteration 1, needs review

#48 Feature/user class and tests
  src/ingredientRepo.js
  src/user.js
  test/user-test.js
Labels: JavaScript, iteration 2, needs review

#54 Feature/user favorites search filter
  src/index.html
  src/scripts.js
  src/user.js
  test/user-test.js
Labels: JavaScript, feature, iteration 2

#55 Feature/remove favorite recipes
  assets/close-circle-outline (1).svg
  src/index.html
  src/scripts.js
  src/style.css
  src/user.js
  test/user-test.js
Labels: JavaScript, iteration 2, needs review

#62 Feature/pantry class and tests
  src/pantry.js
  src/scripts.js
  test/pantry-test.js
Labels: JavaScript, feature, iteration 3, needs review

#65 Feature/create pantry view
  src/index.html
  src/scripts.js
  src/style.css
Labels: CSS, HTML, iteration 3

#66 Feature/user pantry view
  src/index.html
  src/ingredientRepo.js
  src/scripts.js
Labels: JavaScript, iteration 3, needs review

#67 Feature/refactor dom ids and amounts display
  src/index.html
  src/recipe.js
  src/scripts.js
Labels: bug, needs review

#69 Fix/responsive styling
  src/index.html
  src/recipe.js
  src/scripts.js
Labels: CSS, HTML, JavaScript, iteration 3, needs review

#70 Feature/refactor test files
  src/ingredientRepo.js
  src/reciperepo.js
  src/scripts.js
  src/user.js
  test/ingredientRepo-test.js
  test/pantry-test.js
  test/recipe-test.js
  test/reciperepo-test.js
  test/user-test.js
Labels: Refactor, needs review, testing

#72 Fix/all recipe styling
  src/index.html
  src/style.css
Labels: CSS, HTML, bug, iteration 3, needs review

#73 Fix/favorite and pantry boxes
  src/scripts.js
  src/style.css
Labels: CSS, JavaScript, bug, iteration 3, needs review

#74 Fix event handler for favorite recipe click
  src/scripts.js
Labels: JavaScript, bug, iteration 3, needs review

#75 Refactor/format
  src/index.html
  src/scripts.js
  test/recipe-test.js
  test/reciperepo-test.js
  test/user-test.js
Labels: HTML, JavaScript, Refactor, needs review
